apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: browserjs-sessions
resources:
  - job.yaml
configMapGenerator:
  - name: session-disk-migration
    files:
      - migrate.py
